#ifndef PROCESSOR_EMULATOR_INSTRUCTIONS_H
#define PROCESSOR_EMULATOR_INSTRUCTIONS_H

#include "processor.h"

#define INS_LDA_IMMEDIATE 0xA9
#define INS_LDA_ABSOLUTE  0xAD
#define INS_LDA_ABSOLUTE_X 0xBD
#define INS_LDA_ABSOLUTE_Y 0xB9
#define INS_LDA_ZEROPAGE 0xA5
#define INS_LDA_ZEROPAGE_X 0xB5
#define INS_LDA_INDEXED_INDIRECT 0xA1
#define INS_LDA_INDIRECT_INDEXED 0xB1

#define INS_STA_ABSOLUTE 0x8D
#define INS_STA_ABSOLUTE_X 0x9D
#define INS_STA_ABSOLUTE_Y 0x99
#define INS_STA_ZEROPAGE 0x85
#define INS_STA_ZEROPAGE_X 0x95
#define INS_STA_INDEXED_INDIRECT 0x81
#define INS_STA_INDIRECT_INDEXED 0x91

#define INS_LDX_IMMEDIATE 0xA2
#define INS_LDX_ABSOLUTE 0xAE
#define INS_LDX_ABSOLUTE_Y 0xBE
#define INS_LDX_ZEROPAGE 0xA6
#define INS_LDX_ZEROPAGE_Y 0xB6

#define INS_STX_ABSOLUTE 0x8E
#define INS_STX_ZEROPAGE 0x86
#define INS_STX_ZEROPAGE_Y 0x96

#define INS_LDY_IMMEDIATE 0xA0
#define INS_LDY_ABSOLUTE 0xAC
#define INS_LDY_ABSOLUTE_X 0xBC
#define INS_LDY_ZEROPAGE 0xA4
#define INS_LDY_ZEROPAGE_X 0xB4

#define INS_STY_ABSOLUTE 0x8C
#define INS_STY_ZEROPAGE 0x84
#define INS_STY_ZEROPAGE_X 0x94

#define INS_CLC 0x18
#define INS_CLD 0xD8
#define INS_CLI 0x58
#define INS_CLV 0xB8
#define INS_SEC 0x38
#define INS_SED 0xF8
#define INS_SEI 0x78

#define INS_TAX 0xAA
#define INS_TAY 0xA8
#define INS_TXA 0x8A
#define INS_TYA 0x98
#define INS_TSX 0xBA
#define INS_TXS 0x9A

#define INS_INC_ZEROPAGE 0xE6
#define INS_INC_ZEROPAGE_X 0xF6
#define INS_INC_ABSOLUTE 0xEE
#define INS_INC_ABSOLUTE_X 0xFE

#define INS_DEC_ZEROPAGE 0xC6
#define INS_DEC_ZEROPAGE_X 0xD6
#define INS_DEC_ABSOLUTE 0xCE
#define INS_DEC_ABSOLUTE_X 0xDE

#define INS_INX 0xE8
#define INS_DEX 0xCA

#define INS_INY 0xC8
#define INS_DEY 0x88

#define INS_JSR 0x20

#endif
